### PR TITLE
strinp_html returns empty if input is null/empty

### LINKED ISSUE #231: StripHtml can throw exceptions
https://github.com/OrchardCMS/OrchardCore/issues/7448

### PR DESCRIPTION
**Pull request by hishamco**
Fixes #231

### CODE REVIEW

File: Fluid/Filters/MiscFilters.cs [hunk 1]
```diff
@@ -92,32 +92,42 @@ public static FluidValue UrlDecode(FluidValue input, FilterArguments arguments,
...
-            
-            var result = new char[html.Length];
-
-            var cursor = 0;
-            var inside = false;
-            for (var i = 0; i < html.Length; i++)
+            if (String.IsNullOrEmpty(html))
             {
-                char current = html[i];
+                return new StringValue(String.Empty);
```
Comment (sebastienros) [inline Fluid/Filters/MiscFilters.cs:97]:
```suggestion
                return StringValue.Empty;
```

**Review by sebastienros — APPROVED** [review]
