### PR TITLE
Use Parlot

### LINKED ISSUE #242: Using Parlot
Seems a Parlot is shining parser, that have been using in Shortcodes recently, any plan to use in Fluid especially the PERF here is very important for a templating language

I will take some time to check and dig into Parlot, hopefully it's extensible and allow us to expose metadata for exception and others things, coz I remember there was an old issue about geting the error line or column in Irony in Fluid, which has been resolved using hack if I'm not wrong

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #242

- [x] Update extensibility documentation

### CODE REVIEW

File: Fluid.MvcSample/Startup.cs [hunk 1]
```diff
@@ -12,29 +13,39 @@ public class Startup
...
             TemplateContext.GlobalMemberAccessStrategy.Register<Person>();
-            FluidViewTemplate.Factory.RegisterTag<MyTag>("mytag");
         }
 
         // This method gets called by the runtime. Use this method to add services to the container.
         // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
         public void ConfigureServices(IServiceCollection services)
         {
+            services.Configure<FluidViewEngineOptions>(x => x.Parser = p => 
+                p.RegisterEmptyBlock("mytag", async (s, w, e, c) =>
```
Comment (lahma) [inline Fluid.MvcSample/Startup.cs:23]: maybe as static to promote best practices?

File: Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj [hunk 2]
```diff
@@ -1,7 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFramework>netstandard2.0</TargetFramework>
+    <TargetFramework>netstandard2.1</TargetFramework>
```
Comment (lahma) [inline Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj:4]: can this be a problem for people upgrading? no longer usable on full framework

File: Fluid.MvcViewEngine/FluidViewParser.cs [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+using System.IO;
+using System.Threading.Tasks;
+
+namespace Fluid.MvcViewEngine
+{
+    public class FluidViewParser : FluidParser
+    {
+        public FluidViewParser()
+        {
+            RegisterIdentifierTag("rendersection", async (tag, writer, encoder, context) =>
```
Comment (lahma) [inline Fluid.MvcViewEngine/FluidViewParser.cs:14]: maybe statics here too?

**Comment by sebastienros** [comment]
- [ ] Update extensibility documentation

File: Fluid/Ast/CaseStatement.cs [hunk 4]
```diff
@@ -7,39 +8,38 @@ namespace Fluid.Ast
 {
     public class CaseStatement : TagStatement
     {
+        private readonly IReadOnlyList<WhenStatement> _whenStatements;
```
Comment (lahma) [inline Fluid/Ast/CaseStatement.cs:11]: field would ideally be of concrete  type, now foreach will allocate to get enumerator, if interface required then for might be a better option (used elsewhere because of this very reason)

File: Fluid.MvcSample/Startup.cs (hunk 1 above)
Comment (sebastienros) [reply Fluid.MvcSample/Startup.cs:23]: Also I don't like the way I pass a lambda here (x.PArser = p =) I think I should just expose a parser instance so the only lambda is the Configure call

File: Fluid/Ast/CommentStatement.cs [hunk 5]
```diff
@@ -7,17 +7,12 @@ namespace Fluid.Ast
 {
     public class CommentStatement : Statement
     {
-        public CommentStatement(StringSegment text)
-        {
-            Text = text.ToString();
-        }
-
-        public CommentStatement(string text)
+        public CommentStatement(TextSpan text)
```
Comment (lahma) [inline Fluid/Ast/CommentStatement.cs:10]: maybe as `in` parameter, if saved as field property could be `public ref readonly TextSpan =>ref  _text;`

File: Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj (hunk 2 above)
Comment (sebastienros) [reply Fluid.MvcViewEngine/Fluid.MvcViewEngine.csproj:4]: Parlot requirement. ReadOnlySpan ... So if it's fixed it has to be in Parlot

File: Fluid/Ast/CaseStatement.cs (hunk 4 above)
Comment (sebastienros) [reply Fluid/Ast/CaseStatement.cs:11]: Missed some of them apparently

File: Fluid/Ast/IncludeStatement.cs [hunk 6]
```diff
@@ -9,9 +9,11 @@ namespace Fluid.Ast
     public class IncludeStatement : Statement
     {
         public const string ViewExtension = ".liquid";
+        private readonly IFluidParser _parser;
 
-        public IncludeStatement(Expression path, Expression with = null, IList<AssignStatement> assignStatements = null)
+        public IncludeStatement(IFluidParser parser, Expression path, Expression with = null, IList<AssignStatement> assignStatements = null)
```
Comment (lahma) [inline Fluid/Ast/IncludeStatement.cs:14]: can parser be other than `FluidParser `? now it's interface dispatch

File: Fluid/Ast/RawStatement.cs [hunk 7]
```diff
@@ -0,0 +1,24 @@
+﻿using Parlot;
+using System.IO;
+using System.Text.Encodings.Web;
+using System.Threading.Tasks;
+
+namespace Fluid.Ast
+{
+    public class RawStatement : Statement
+    {
+        public RawStatement(TextSpan text)
```
Comment (lahma) [inline Fluid/Ast/RawStatement.cs:10]: maybe `in` and `ref readonly`?

File: Fluid/Ast/TextSpanStatement.cs [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+namespace Fluid.Ast
+{
+    public class TextSpanStatement : Statement
+    {
+        private bool _isStripped = false;
+        private bool _isEmpty = false;
+        private readonly object _synLock = new object();
+        private TextSpan _text;
+
+        public TextSpanStatement(TextSpan text)
```
Comment (lahma) [inline Fluid/Ast/TextSpanStatement.cs:15]: `in`?

File: Fluid/Ast/TextSpanStatement.cs [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+        {
+            StrippedRight = true;
+        }
+
+        public void StripLeft()
+        {
+            StrippedLeft = true;
+        }
+
+        public TextSpan Text => _text;
```
Comment (lahma) [inline Fluid/Ast/TextSpanStatement.cs:38]: `ref readonly`?

File: Fluid/Ast/TextSpanStatement.cs [hunk 10]
```diff
@@ -0,0 +1,135 @@
...
+
+        public override ValueTask<Completion> WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
+        {
+            // Prevent this instance from mutating concurrently
+
+            if (!_isStripped)
+            {
+                lock (_synLock)
```
Comment (lahma) [inline Fluid/Ast/TextSpanStatement.cs:46]: can this lock be shorter? like calculating the end result and then finally taking the lock? don't know the contention amounts here

File: Fluid/Fluid.csproj [hunk 11]
```diff
@@ -1,30 +1,19 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>netstandard2.0;netstandard2.1;net461;netcoreapp3.1;net5.0</TargetFrameworks>
+    <TargetFrameworks>netstandard2.1;netcoreapp3.1;net5.0</TargetFrameworks>
```
Comment (lahma) [inline Fluid/Fluid.csproj:4]: will strip full framework here too, probably major version bump if intended

File: Fluid/Parser/TagParsers.cs [hunk 12]
```diff
@@ -0,0 +1,196 @@
...
+    }
+
+    public static class TagParsers
+    {
+        public static Parser<TagResult> TagStart(bool skipWhiteSpace = false) => new TagStartParser(skipWhiteSpace);
+        public static Parser<TagResult> TagEnd(bool skipWhiteSpace = false) => new TagEndParser(skipWhiteSpace);
+        public static Parser<TagResult> OutputTagStart(bool skipWhiteSpace = false) => new OutputTagStartParser(skipWhiteSpace);
+        public static Parser<TagResult> OutputTagEnd(bool skipWhiteSpace = false) => new OutputTagEndParser(skipWhiteSpace);
+
+        private class TagStartParser : Parser<TagResult>
```
Comment (lahma) [inline Fluid/Parser/TagParsers.cs:39]: sealed if possible

File: Fluid/Parser/TagParsers.cs [hunk 13]
```diff
@@ -0,0 +1,196 @@
...
+                    return true;
+                }
+                else
+                {
+                    return false;
+                }
+            }
+        }
+
+        private class TagEndParser : Parser<TagResult>
```
Comment (lahma) [inline Fluid/Parser/TagParsers.cs:80]: sealed if possible

File: Fluid/Parser/TagParsers.cs [hunk 14]
```diff
@@ -0,0 +1,196 @@
...
+                    return true;
+                }
+                else
+                {
+                    return false;
+                }
+            }
+        }
+
+        private class OutputTagStartParser : Parser<TagResult>
```
Comment (lahma) [inline Fluid/Parser/TagParsers.cs:117]: sealed if possible

File: Fluid/Parser/TagParsers.cs [hunk 15]
```diff
@@ -0,0 +1,196 @@
...
+                    return true;
+                }
+                else
+                {
+                    return false;
+                }
+            }
+        }
+
+        private class OutputTagEndParser : Parser<TagResult>
```
Comment (lahma) [inline Fluid/Parser/TagParsers.cs:159]: sealed if possible

**Comment by lahma** [comment]
One other thing,  ideally use throwhelper so constructors etc could be inlined, throw will prohibit that

File: Fluid/Ast/TextSpanStatement.cs (hunk 9 above)
Comment (sebastienros) [reply Fluid/Ast/TextSpanStatement.cs:38]: _text is mutated

File: Fluid/Fluid.csproj [hunk 16]
```diff
@@ -10,21 +10,20 @@
...
-  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.1'">
+  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
     <PackageReference Include="System.Text.Json" Version="4.7.2" />
     <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
   </ItemGroup>
-
-  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.1'">
-  </ItemGroup>
-
-  <ItemGroup Condition="'$(TargetFramework)'=='net5.0'">
```
Comment (hishamco) [inline Fluid/Fluid.csproj:38]: Why we remove other target frameworks?!!

Comment (sebastienros) [reply Fluid/Fluid.csproj:38]: I couldn't give why I added them. Can you think of any reason to keep them?

Comment (hishamco) [reply Fluid/Fluid.csproj:38]: May be you added them when it's `netcoreapp` not `netstandard`

Comment (sebastienros) [reply Fluid/Fluid.csproj:38]: I think that since it's targeting netstd20 and netstd21, __and__ there is no specific dependency that could go away with netcoreapp, then it's not required to target netcoreapp.

Comment (hishamco) [reply Fluid/Fluid.csproj:38]: is the PR functional ready, I'd like to test few cases

Comment (sebastienros) [reply Fluid/Fluid.csproj:38]: You should pay more attention to what I wrote, because I was looking at the csproj and realized that the netcoreapp targets actually remove some dependencies, so I am adding them back! With a comment this time ;)

Comment (sebastienros) [reply Fluid/Fluid.csproj:38]: It's ready, I will push a v1 with the current master, create a release/1.x branch to follow up, and then start v2 by merging this one on master. At the same time migrate to "main"

File: README.md [hunk 17]
```diff
@@ -153,21 +156,23 @@ To create an **async** filter use the `AddAsyncFilter` method instead.
...
+### Allow-listing a specific type
 
 This will allow any public field or property to be read from a template.
 
 ```csharp
 TemplateContext.GlobalMemberAccessStrategy.Register<Person>();
 ``` 
 
-### White-listing specific members
+> Note: When passing a model with `new TemplateContext(model)` the type of the `model` object doesnis automatically registered, unless the `registerModelProperties` argument is set to false.
```
Comment (lahma) [inline README.md:173]: Typo "doesnis"
