### PR TITLE
Fix `StringValue.Create` encode overload.

### LINKED ISSUE #749: bug: Recursive function call
Liquid:
```html
{{ localize('Teste')}} 
```

Function impl:

```cs
    public FunctionValue GetLocalizeFunction()
    {
        var localize = new FunctionValue((args, _) =>
        {
            var firstArg = args.At(0).ToStringValue();
            var localizerArgs = args.Values.Skip(1).Select(v => v.ToStringValue()).ToArray();

            var localizedString = stringLocalizer[firstArg, localizerArgs.ToArray()];

            return StringValue.Create(localizedString, encode: true);
        });
        return localize;
    }
``` 
Stacktrace:
```cs
Stack overflow.
Repeated 174380 times:
--------------------------------
   at Fluid.Values.StringValue.Create(System.String, Boolean)
--------------------------------
   at JJMasterData.Core.Html.Templates.HtmlTemplateHelper.<GetLocalizeFunction>b__6_0(Fluid.FunctionArguments, Fluid.TemplateContext)
   at Fluid.Values.FunctionValue+<>c__DisplayClass3_0.<.ctor>b__0(Fluid.FunctionArguments, Fluid.TemplateContext)
   at Fluid.Values.FunctionValue.InvokeAsync(Fluid.FunctionArguments, Fluid.TemplateContext)
   at Fluid.Ast.FunctionCallSegment+<ResolveAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Fluid.Ast.FunctionCallSegment+<ResolveAsync>d__6, Fluid, Version=2.18.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789]](<ResolveAsync>d__6 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Fluid.Ast.FunctionCallSegment+<ResolveAsync>d__6, Fluid, Version=2.18.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789]](<ResolveAsync>d__6 ByRef)
   at Fluid.Ast.FunctionCallSegment.ResolveAsync(Fluid.Values.FluidValue, Fluid.TemplateContext)
   at Fluid.Ast.MemberExpression.EvaluateAsync(Fluid.TemplateContext)
   at Fluid.Ast.OutputStatement.WriteToAsync(System.IO.TextWriter, System.Text.Encodings.Web.TextEncoder, Fluid.TemplateContext)
   at Fluid.Parser.FluidTemplate.RenderAsync(System.IO.TextWriter, System.Text.Encodings.Web.TextEncoder, Fluid.TemplateContext)
   at Fluid.FluidTemplateExtensions+<RenderAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Fluid.FluidTemplateExtensions+<RenderAsync>d__3, Fluid, Version=2.18.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789]](<RenderAsync>d__3 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Fluid.FluidTemplateExtensions+<RenderAsync>d__3, Fluid, Version=2.18.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789]](<RenderAsync>d__3 ByRef)
   at Fluid.FluidTemplateExtensions.RenderAsync(Fluid.IFluidTemplate, Fluid.TemplateContext, System.Text.Encodings.Web.TextEncoder, Boolean)
   at JJMasterData.Core.Html.Templates.HtmlTemplateRenderer.RenderTemplate(System.String, System.Collections.Generic.Dictionary`2<System.String,System.Object>)
   at JJConsulting.Infinity.Lib.DynamicPages.Services.DynamicPageService+<RenderTemplate>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at JJConsulting.Infinity.Lib.DynamicPages.Services.DynamicPageService.RenderTemplate(JJConsulting.Infinity.Lib.DynamicPages.Models.DynamicTemplate)
   at JJConsulting.Infinity.Web.Areas.Admin.Controllers.DynamicPagesController+<Editor>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at JJConsulting.Infinity.Web.Areas.Admin.Controllers.DynamicPagesController.Editor(JJConsulting.Infinity.Lib.DynamicPages.Models.DynamicPageModel)
   at DynamicClass.lambda_method1084(System.Runtime.CompilerServices.Closure, System.Object, System.Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfActionResultExecutor+<Execute>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfActionResultExecutor+<Execute>d__0, Microsoft.AspNetCore.Mvc.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<Execute>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7
``` 

Fluid bug:
Image

### PR DESCRIPTION
**Pull request by gumbarros**
This closes #749

### CODE REVIEW

File: Fluid/Values/StringValue.cs [hunk 1]
```diff
@@ -70,7 +70,7 @@ public static StringValue Create(string s)
         [MethodImpl(MethodImplOptions.AggressiveInlining)]
         public static StringValue Create(string s, bool encode)
         {
-            return Create(s, encode);
+            return Create(encode ? HtmlEncoder.Default.Encode(s) : s);
```
Comment (sebastienros) [inline Fluid/Values/StringValue.cs:73]: This should return the constructor that takes these two arguments.
