### PR TITLE
Fix async pattern in RenderAsync

### LINKED ISSUE #428: FluidTemplateExtensions.RenderAsync premature release scope
The method:
```csharp
public static ValueTask<string> RenderAsync(this IFluidTemplate template, TemplateContext context, TextEncoder encoder)
```
ReleaseScope in finally block.

When my template running too long, scope premature released .

I write some test code :

```csharp
var parser = new FluidParser();

parser.RegisterEmptyBlock("sleep", async (statements, writer, encoder, context) =>
 {
	 context.EnterChildScope();
	 context.IncrementSteps();
	 context.SetValue("id", "123");
	 await Task.Delay(100);
	 await statements.RenderStatementsAsync(writer, encoder, context);
	 context.ReleaseScope();
	 return Completion.Normal;
 });


var context = new TemplateContext {};
context.SetValue("id","000");
var template = parser.Parse(@"{{id}}
{%sleep%}{{id}}{%endsleep%}
{{id}}
");
 
var output = await template.RenderAsync(context);

Console.WriteLine(output);
```

Output: 
```
000
000
000
```

But,the right output should be:

```
000
123
000
```

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #428

### CODE REVIEW

**Review by lahma — APPROVED** [review]
Looks good, pretty much the same where to I reduced the code to get it working.

File: Fluid/FluidTemplateExtensions.cs [hunk 1]
```diff
@@ -44,45 +44,25 @@ public static ValueTask<string> RenderAsync(this IFluidTemplate template, Templa
...
-            }
-
             var sb = StringBuilderPool.GetInstance();
             var writer = new StringWriter(sb.Builder);
 
+            // A template is evaluated in a child scope such that the provided TemplateContext is immutable
+            context.EnterChildScope();
+
             try
             {
```
Comment (hishamco) [inline Fluid/FluidTemplateExtensions.cs:54]: What will be returns if an exception is occured?!!

Comment (sebastienros) [reply Fluid/FluidTemplateExtensions.cs:54]: And Exception

Comment (hishamco) [reply Fluid/FluidTemplateExtensions.cs:54]: So this intentionally?!! coz isn't throw before

Comment (hishamco) [reply Fluid/FluidTemplateExtensions.cs:54]: Probably we need a remark on that method to make clear to everyone

Comment (lahma) [reply Fluid/FluidTemplateExtensions.cs:54]: I don't think the behavior has changed here. New code just awaits to prevent control flow from getting out with unfinished continuations that could run after finally has been processed.

Comment (hishamco) [reply Fluid/FluidTemplateExtensions.cs:54]: What confuses me the old behavior returns the actual string from the ` StringBuilderPool` instace in both case (Exception or Without Exception) but now the string is returned if no exception occurs. Am I right?

Comment (lahma) [reply Fluid/FluidTemplateExtensions.cs:54]: The old code would have done the `await` on `Awaited` method which would have bubbled the exception. So both versions will throw, this one obeys template context life time.

Comment (sebastienros) [reply Fluid/FluidTemplateExtensions.cs:54]: Wrong, if there had been an exception, it would have been thrown by the task that is returned.
No exception is caught here, so everything will bubble up.
